# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-schema"
client_id = "3b107af0289e08f31d90519e4c0ef68d"
application_url = "https://test-schema-ebcd8f4ce048.herokuapp.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,write_content"

[auth]
redirect_urls = [
  "https://test-schema-ebcd8f4ce048.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5a5be50d.myshopify.com"
