# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "schema-test"
client_id = "fab1bfb0443aa61fe2368c2f77e8c0d9"
application_url = "https://alexander-phenomenon-dealt-clan.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,write_content"

[auth]
redirect_urls = [
  "https://alexander-phenomenon-dealt-clan.trycloudflare.com/auth/callback",
  "https://alexander-phenomenon-dealt-clan.trycloudflare.com/auth/shopify/callback",
  "https://alexander-phenomenon-dealt-clan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5a5be50d.myshopify.com"
