# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-balwan"
client_id = "2e1f049b36e39b11ef16bce68375e40c"
application_url = "https://scary-junction-fine-fo.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,write_content"

[auth]
redirect_urls = [
  "https://scary-junction-fine-fo.trycloudflare.com/auth/callback",
  "https://scary-junction-fine-fo.trycloudflare.com/auth/shopify/callback",
  "https://scary-junction-fine-fo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5a5be50d.myshopify.com"
